store_backend_homepage:
    path:     /hello/{name}
    defaults: { _controller: storeBackendBundle:Default:index }


# nom de la route
store_backend_index:
    path:     /dashboard  #chemin / URI de la route Url afficher
    defaults: { _controller: storeBackendBundle:Main:index } # le controlleur et l'action Main le nom de fichier controleur

store_backend_statics:
    resource: "@storeBackendBundle/Resources/config/statics.yml"
    prefix:   /

store_backend_product:
    resource: "@storeBackendBundle/Resources/config/modules/product.yml"
    prefix:   /products

store_backend_categories:
    resource: "@storeBackendBundle/Resources/config/modules/category.yml"
    prefix:   /categories

store_backend_CMS:
    resource: "@storeBackendBundle/Resources/config/modules/cms.yml"
    prefix:   /CMS
