# Page Static Contact
store_backend_statics_contact:
    path:     /contact #chemin vers l'URI
    defaults: { _controller: StoreBackendBundle:Statics:contact }
    # NomduBundle:NomduControlleur:Nomdel'Action
